### PR TITLE
Fix LICENSE copyright example

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Review by tkolcon — CHANGES_REQUESTED** [review]
Should be "2020 Łukasiewicz-PIAP"

**Comment by ralph-lange** [comment]
No, it should be "2020 Łukasiewicz-PIAP" in the headers of your source files only. In the LICENSE file, this paragraph explains in general how to apply the Apache 2.0 license. Therefore it should be the original text, which was `Copyright [yyyy] [name of copyright owner]`.

**Comment by ralph-lange** [comment]
See the bottom of https://www.apache.org/licenses/LICENSE-2.0.txt

**Review by tkolcon — APPROVED** [review]

**Comment by tkolcon** [comment]
I undestood.

**Pull request merged**
